language: bash
sudo: required
services:
- docker
before_script:
- openssl aes-256-cbc -K $encrypted_9cc1f37f0fdd_key -iv $encrypted_9cc1f37f0fdd_iv
  -in khs1994-robot.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "khs1994-merge-robot"
- git config --global user.email "ai@khs1994.com"
- export TZ='Asia/Shanghai'
- date
- export DEPLOY_BRANCH=gh-pages
script:
- cd ~
- export REPO=$REPO_4
- export REPO_ALIYUN=$REPO_ALIYUN_4
- git clone --depth=10 --branch=5.5 $REPO repo
- cd repo
- "~/build/khs1994-gitbook/gitbook-travis/deploy.sh"
- cd ~
- export REPO=$REPO_5
- export REPO_ALIYUN=$REPO_ALIYUN_5
- git clone --depth=10 --branch=5.5 $REPO repo
- cd repo
- "~/build/khs1994-gitbook/gitbook-travis/deploy.sh"
- cd ~
# - export REPO=$REPO_6
# - export REPO_ALIYUN=$REPO_ALIYUN_6
# - git clone --depth=10 --branch=5.4 $REPO repo
# - cd repo
# - "~/build/khs1994-gitbook/gitbook-travis/deploy.sh"
# - cd ~
install:
- echo $PWD
env:
  global:
  - REPO_4: git@github.com:khs1994-gitbook/laravel-docs-en.git
  - REPO_5: git@github.com:khs1994-gitbook/laravel-docs.git
  - REPO_6: git@github.com:khs1994-gitbook/laravel-5.4.git
addons:
  ssh_known_hosts:
  - github.com
branches:
  only:
  - master
