language: bash
sudo: required
services:
- docker
before_script:
- openssl aes-256-cbc -K $encrypted_9cc1f37f0fdd_key -iv $encrypted_9cc1f37f0fdd_iv
  -in khs1994-robot.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "khs1994-merge-robot"
- git config --global user.email "ai@khs1994.com"
- export TZ='Asia/Shanghai'
- date
- export DEPLOY_BRANCH=gh-pages
script:
- cd ~
- git clone --depth=1 git@github.com:feiskyer/kubernetes-handbook.git k8s
- cd k8s/zh
- cp $TRAVIS_BUILD_DIR/k8s/book.json book.json
- export REPO=$REPO_1
- $TRAVIS_BUILD_DIR/deploy.sh

- cd ~
- export REPO=$REPO_2
- git clone --depth=1 $REPO repo
- cd repo
- $TRAVIS_BUILD_DIR/deploy.sh

# - cd ~
# - export REPO=$REPO_3
# - git clone --depth=1 $REPO repo
# - cd repo
# - $TRAVIS_BUILD_DIR/deploy.sh

- cd ~
- git clone --depth=1 git@github.com:DocsHome/nginx-docs.git
- cd nginx-docs
- export REPO=$REPO_4
- $TRAVIS_BUILD_DIR/deploy.sh
- cd ~
install:
- echo $PWD
env:
  global:
  - REPO_1: git@github.com:khs1994-website/kubernetes-handbook.git
  - REPO_2: git@github.com:khs1994-website/laravel-docs.git
  # - REPO_3: git@github.com:khs1994-website/laravel5.5-docs.git
  - REPO_4: git@github.com:khs1994-website/nginx-docs.zh-cn.git
addons:
  ssh_known_hosts:
  - github.com
branches:
  only:
  - master
